Ecommercemvcapp/Models/Producer.cs
using System.ComponentModel.DataAnnotations;
using Ecommercemvcapp.Data.Base;

namespace Ecommercemvcapp.Models
{
    public class Producer:IEntityBase
    {

        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name ="Profile picture")]
        public string? ProfileImageUrl { get; set; }
        [Required]
        [StringLength(50)]
        public string? FullName { get; set; }
        [Required]
        [StringLength (maximumLength:500)]
        public string? Biografy { get; set; }
        
        //Relations
        public List<Movie> Movies { get; set; }
    }
}

Ecommercemvcapp/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommercemvcapp.Data;
using Microsoft.EntityFrameworkCore;
using Ecommercemvcapp.Data.Services;
using Ecommercemvcapp.Models;

namespace Ecommercemvcapp.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducerServices _service;

        public ProducersController(IProducerServices service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var producersdata = await _service.GetAllAsync();
            return View(producersdata);
        }
       
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Producer producer)
            {
            //if(!ModelState.IsValid)
            //{
            //    return View(producer);
            //}
            await _service.AddAsync(producer);
           return RedirectToAction(nameof(Index));
        }
        //Get: /Producers/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null)
            {
                return View("Notfound");
            }
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
           
            var result = await _service.GetByIdAsync(id);
            if(result == null)
            {
                return View("Notfound");
            }
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,Producer producer)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(producer);
            //}
            await _service.UpdateAsync(id, producer);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if (result == null)
            {
                return View("Notfound");
            }
            return View(result);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Ecommercemvcapp/Views/Producers/Create.cshtml
@model Ecommercemvcapp.Models.Producer
@{
    ViewBag.Title = "Create Producer";

}
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h5>Add A New Producer</h5>
        </p>
    </div>
    <div class="row">
        <div class="col-md-8 offset-2">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                
                 <div class="form-group text-center">
                     <img id="ProfilePictirePreview" />
                 </div>

                 <div class="form-group">
                     <label asp-for="ProfileImageUrl" class="control-label"></label>
                     <input asp-for="ProfileImageUrl" class="form-control" />
                     <span asp-validation-for="ProfileImageUrl" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="FullName" class="control-label"></label>
                     <input asp-for="FullName" class="form-control" />
                     <span asp-validation-for="FullName" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="Biografy" class="control-label"></label>
                     <input asp-for="Biografy" class="form-control" />
                     <span asp-validation-for="Biografy" class="text-danger"></span>
                 </div>
                 <div class="form-group">
                     <input  type="submit" value="Create" class="btn btn-primary float-end" />
                     <a asp-action="Index" asp-controller="Producers" class="btn btn-secondary">show All</a>

                 </div>
            </form>
        </div>
       

    </div>
</div>

@section scripts{
    <script>
        $("#ProfileImageUrl").on("change",function(){
            var output = document.getElementById('ProfilePictirePreview');
            output.src = $(this).val();
        })
    </script>
}

Ecommercemvcapp/Views/Producers/Delete.cshtml
@model Ecommercemvcapp.Models.Producer
@{
    ViewBag.Title = "Delete a Producer";

}
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h5>Delete @Model.FullName</h5>
        </p>
    </div>
    <div class="row">
        <div class="col-md-8 offset-2">
            
               
                
                 <div class="form-group text-center">
                     <img id="ProfilePictirePreview" />
                 </div>

                 <div class="form-group">
                     <label asp-for="ProfileImageUrl" class="control-label"></label>
                     <input asp-for="ProfileImageUrl" class="form-control" readonly />
                     <span asp-validation-for="ProfileImageUrl" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="FullName" class="control-label"></label>
                     <input asp-for="FullName" class="form-control" readonly />
                     <span asp-validation-for="FullName" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="Biografy" class="control-label"></label>
                     <input asp-for="Biografy" class="form-control" readonly />
                     <span asp-validation-for="Biografy" class="text-danger"></span>
                 </div>
                 <div class="form-group">
                     <form asp-action ="Delete">
                         <input type="hidden" asp-for="Id"/>
                         <input  type="submit" class="btn btn-danger float-end" value="confirm"/>
                     </form>
                    
                     <a asp-action="Index" asp-controller="Producers" class="btn btn-secondary">show All</a>

                 </div>
           
        </div>
       

    </div>
</div>

@section scripts{
    <script>

        $(document).ready(function()
        {
            var output = document.getElementById('ProfilePictirePreview');
            output.src = $('#ProfileImageUrl').val();

        })
        
    </script>
}

Ecommercemvcapp/Views/Producers/Details.cshtml
@model Ecommercemvcapp.Models.Producer
@{
    ViewBag.Title = "Producer dettils";

}
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h5>Details of @Model.FullName</h5>
        </p>
    </div>
    <div class="row">
        <div class="col-md-8 offset-2">
            
               
                
                 <div class="form-group text-center">
                     <img id="ProfilePictirePreview" />
                 </div>

                 <div class="form-group">
                     <label asp-for="ProfileImageUrl" class="control-label"></label>
                     <input asp-for="ProfileImageUrl" class="form-control" readonly />
                     <span asp-validation-for="ProfileImageUrl" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="FullName" class="control-label"></label>
                     <input asp-for="FullName" class="form-control" readonly />
                     <span asp-validation-for="FullName" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="Biografy" class="control-label"></label>
                     <input asp-for="Biografy" class="form-control" readonly />
                     <span asp-validation-for="Biografy" class="text-danger"></span>
                 </div>
                 <div class="form-group">
                    
                     <a asp-action="Index" asp-controller="Producers" class="btn btn-secondary">show All</a>

                 </div>
           
        </div>
       

    </div>
</div>

@section scripts{
    <script>

        $(document).ready(function()
        {
            var output = document.getElementById('ProfilePictirePreview');
            output.src = $('#ProfileImageUrl').val();

        })
        
    </script>
}

Ecommercemvcapp/Views/Producers/Edit.cshtml
@model Ecommercemvcapp.Models.Producer
@{
    ViewBag.Title = "Update Producer";

}
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h5>Update a Producer</h5>
        </p>
    </div>
    <div class="row">
        <div class="col-md-8 offset-2">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                
                 <div class="form-group text-center">
                     <img id="ProfilePictirePreview" style="max-width:100px" />
                 </div>

                 <div class="form-group">
                     <label asp-for="ProfileImageUrl" class="control-label"></label>
                     <input asp-for="ProfileImageUrl" class="form-control" />
                     <span asp-validation-for="ProfileImageUrl" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="FullName" class="control-label"></label>
                     <input asp-for="FullName" class="form-control" />
                     <span asp-validation-for="FullName" class="text-danger"></span>
                 </div>
                  <div class="form-group">
                     <label asp-for="Biografy" class="control-label"></label>
                     <input asp-for="Biografy" class="form-control" />
                     <span asp-validation-for="Biografy" class="text-danger"></span>
                 </div>
                 <div class="form-group">
                     <input  type="submit" value="Edit" class="btn btn-primary float-end" />
                     <a asp-action="Index" asp-controller="Producers" class="btn btn-secondary">show All</a>

                 </div>
            </form>
        </div>
       

    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function(){
            var ouput = document.getElementById('ProfilePictirePreview');
            ouput.src = $('#ProfileImageUrl').val();
        })
        $("#ProfileImageUrl").on("change",function(){
            var output = document.getElementById('ProfilePictirePreview');
            output.src = $(this).val();
        })
    </script>
}

Ecommercemvcapp/Views/Producers/Index.cshtml
@model IEnumerable<Ecommercemvcapp.Models.Producer>
@{
    ViewBag.Title = "List of producers";
}
<div class="row">
        <div class="col-md-8 offset-md-2 ">
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>              
                        <th>@Html.DisplayNameFor(model =>model.ProfileImageUrl)</th>
                         <th>@Html.DisplayNameFor(model =>model.FullName)</th>
                          <th>@Html.DisplayNameFor(model =>model.Biografy)</th>
                            @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                 <th>Actions</th>
                            }
                   
                    </tr>
                </thead>
                <tbody >
                  @foreach(var item in Model)
                {
                    <tr style="width:50px">
                        <td class="align-middle">
                            <img class="card" src="@item.ProfileImageUrl" alt="@item.FullName" style="width:100px"> 
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                         <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Biografy)
                        </td>
                         @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                 <td class="align-middle">
                                <a class="btn btn-primary"asp-controller="Producers" asp-action="Edit" asp-route-id=@item.Id><i class="bi bi-pencil"></i>Edit</a>
                                <a class="btn btn-info"asp-controller="Producers" asp-action="Details" asp-route-id=@item.Id><i class="bi bi bi-eye"></i>Details</a>
                                <a class="btn btn-danger"asp-controller="Producers" asp-action="Delete" asp-route-id=@item.Id><i class="bi bi-trash3"></i>Delete</a>
                            </td>
                            }
                       
                    </tr>
                }
            </tbody>
            </table>
        </div>
    </div>
     @await Html.PartialAsync("_Createitem","Producers")