Ecommercemvcapp/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommercemvcapp.Data;
using Ecommercemvcapp.Data.Services;
using Ecommercemvcapp.Models;

namespace Ecommercemvcapp.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorservices _services;

        public ActorsController(IActorservices service)
        {
            _services = service;
        }
        public async  Task<IActionResult> Index()
        {
            var data = await _services.GetAllAsync();
            return View(data);
        }
        //Get: Actors/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Actor actor)
        {
            if (ModelState.IsValid)
            {
                
                return View(actor);
            }
            

            await _services.AddAsync(actor);
            return RedirectToAction(nameof(Index));
          
        }
        //get : Actors/Details
        public async Task<IActionResult> Details(int id)
        {
          var details = await _services.GetByIdAsync(id);
            if(details == null)
                return View("Notfound");
            else
            return View(details);
        }
        //Get: Actors/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var details = await _services.GetByIdAsync(id);
            if (details == null)
                return View("Notfound");
            else
                return View(details);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,Actor actor)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(actor);
            //}
            await _services.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));

        }
        //Get: Actors/Delete/1

        public async Task<IActionResult> Delete(int id)
        {
            var details = await _services.GetByIdAsync(id);
            if (details == null)
                return View("Notfound");
            else
                return View(details);
        }
        [HttpPost, ActionName("Delete")]    
        public async Task<IActionResult> Deleteconfimed(int id)
        {
            //var details = await _services.GetByIdAsync(id);
            //if (details == null)
            //    return View("Notfound");

            await _services.DeleteAsync(id);
            return RedirectToAction(nameof(Index)); 
        }
    }
}

Ecommercemvcapp/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommercemvcapp.Data;
using Microsoft.EntityFrameworkCore;

namespace Ecommercemvcapp.Controllers
{
    public class CinemasController : Controller
    {
        private readonly AppDbContext _context;

        public CinemasController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var cinemassdata = await _context.Cinemas.ToListAsync();
            return View(cinemassdata);
        }
    }
}

Ecommercemvcapp/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommercemvcapp.Data;
using Microsoft.EntityFrameworkCore;

namespace Ecommercemvcapp.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppDbContext _context;

        public MoviesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var moviesdata = await _context.Movies.Include(n => n.Cinema).ToListAsync();
            return View(moviesdata);
        }
    }
}

Ecommercemvcapp/Controllers/OrdersController.cs
using Ecommercemvcapp.Data.Cart;
using Ecommercemvcapp.Data.Services;
using Ecommercemvcapp.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Ecommercemvcapp.Controllers
{
    public class OrdersController : Controller
    {
        public readonly IMoviesServices _moviServices;
        public readonly ShoppingCart _cart;

        public OrdersController(IMoviesServices moviServices, ShoppingCart cart)
        {
            _moviServices = moviServices;
            _cart = cart;
        }
        public IActionResult Index()
        {
            var items = _cart.GetShoppingCartItems();
            _cart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                shoppingCart = _cart,
                ShoppingCartTotal = _cart.ShoppingitemsTotal()
        };
            return View(response);
        }
    }
}

Ecommercemvcapp/Views/Shared/Notfound.cshtml
<div class="row">
    <div class="col-md-8 offset-3" >
    <h1 class="text-info">
        Not found this data
    </h1>
    <br />
    <a class="btn btn-outline-info" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

Ecommercemvcapp/Views/Shared/_Createitem.cshtml
@model string;

 @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position:fixed;right:25px;bottom:25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i>Abb New</a>
    </div>
}

Ecommercemvcapp/Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<ApplicationUser> UserManager;

@if(!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
                        <span class="bi bi-box-arrow-in-right"></span>Login
                    </a>
                     <span style="padding:5px;"></span>
                     <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
                        <span class="bi bi-person-plus"></span>Register
    </a>
}
else
{
    @*User profile section*@

<div class="dropdown">
    <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn"
    data-toggle="dropdown" aria-expanded="false">
    <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
</button>
<ul class="dropdown-menu" aria-labelledby="profile-btn">
    <li>
        <a class="dropdown-item" asp-action="Index" asp-controller="Orders"></a>
        <i class="bi bi-list"></i>Orders
    </li>
</ul>
</div>
 <span style="padding:5px;"></span>

                    <form asp-controller="Account" asp-action="Logout">
                        <button class="btn btn-outline-danger my-2 my-sm-0">
                            <i class="bi bi-box-arrow-in-right"></i>Logout
                        </button>
                    </form>


}


                    

Ecommercemvcapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommercemvcapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecommercemvcapp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">Ecommercemvcapp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">
                                <i class=" badge-info bi-film"></i>Movies</a>
                        </li>
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                              <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="bi bi-gear"></i> Management
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                        <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                        <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                    </div>
                                </li>
                        }

                       
                    </ul>
                     <form class="form-inline " asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2"/>
                        <button class="btn btn-outline-success " type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    
                   
                    

                   <partial name="_Identity.cshtml"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Ecommercemvcapp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>